#!/bin/bash

echo "Scaling the messaging-app-deployment to 3 replicas..."
kubectl scale deployment  messaging-app-deployment --replicas=3

echo "verifying running pods..."
kubectl get pods -o wide

echo "Starting load testing with wrk..."
wrk -t4 -c50 -d30s https://127.0.0.1:8000/ &

echo "Monitoring resource usage..."
kubectl top pods